#ifndef PROTOCOL_PATIENTADMIN_CENTRALACQ_H
#define PROTOCOL_PATIENTADMIN_CENTRALACQ_H


typedef enum {
	MSG_START_SYMBOL = '$', 
	MSG_END_SYMBOL = '#',
	MSG_ARGUMENT_SEPARATOR = ':'
} SYMBOLS;

typedef enum {
	EXAM_TYPE_SINGLE_SHOT,
	EXAM_TYPE_SERIES,
	EXAM_TYPE_SERIES_WITH_MOTION, 
	EXAM_TYPE_FLUORO,
	EXAM_TYPE_NONE
} EXAMINATION_TYPES;

#define MAX_MSG_SIZE 	(100)



#endif